# Generated by Django 4.2.3 on 2023-07-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_donor_blood_alter_donor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='looking',
            name='dob',
            field=models.DateField(),
        ),
    ]
