# Generated by Django 4.2.3 on 2023-07-31 09:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_donor_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
