# Generated by Django 4.2.3 on 2023-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_looking_dob_alter_looking_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='looking',
            name='require',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
