# Generated by Django 4.2.3 on 2023-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_organ_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='donate_tissue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
