# Generated by Django 4.2.3 on 2023-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_organ_donate_alter_organ_donate_tissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='other',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
