# Generated by Django 4.2.3 on 2023-08-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_bloodgroup_compatibility_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatibility',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='compatibility',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='BloodGroup',
        ),
        migrations.DeleteModel(
            name='Compatibility',
        ),
    ]
