# Generated by Django 4.2.3 on 2023-08-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_searchquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchQuery',
        ),
    ]
