# Generated by Django 4.2.3 on 2023-08-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_searchquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='district',
        ),
        migrations.RemoveField(
            model_name='looking',
            name='district',
        ),
        migrations.RemoveField(
            model_name='organ',
            name='district',
        ),
    ]
